### ISSUE TITLE
Complete the cache/dist cache docs

### ISSUE THREAD

**Issue by Shazwazza** [umbraco/UmbracoDocs#208] opened 2015-08-21 14:46 UTC
/documentation/Reference/Cache/

**Comment by dampee** [comment] 2017-06-12 22:44
Question about [DistributedCacheExtensions](https://github.com/umbraco/Umbraco-CMS/blob/47dbb648fb38fce6b65fb4af3dd7a31033ec574a/src/Umbraco.Web/Cache/DistributedCacheExtensions.cs).  

That is a internal class, why would that be necessary to explain in the documentation?
Or is it the intention to make this class public to the big cruel world?

**Comment by dampee** [comment] 2017-06-12 22:50
Also:
I can't find `DistributedCache.CacheChanged`.  I guess this does not exists anymore.
Same for `DistributedCache.Current`, only `.Instance` is there.  I guess .Current is old stuff?

**Comment by dampee** [comment] 2018-03-13 16:49
Created a pull request (work in progress) #711

**Comment by Shazwazza** [comment] 2018-08-03 02:47
Just FYI, i've had to get some of these docs written, i've added the info directly to the main doc https://github.com/umbraco/UmbracoDocs/blob/master/Reference/Cache/index.md ... i didn't want to change too much but you can probably re-use/move, etc... this info for this PR.

**Comment by jmayntzhusen** [comment] 2019-02-28 09:44
Hi there!

As this issue has been here for over a year without any PRs, we have decided to close it down. 
If you feel the problem is still there, then please open a new issue with as many details as you can so someone has a chance to work on it!

Thanks for reporting it in the first place! 🙂

**Closed by jmayntzhusen** 2019-02-28 09:44 UTC
Labels: category/missing-documentation
