### ISSUE TITLE
"Could not get content type with id" should be added to Cloud troubleshooting section

### ISSUE THREAD

**Issue by tormnator** [umbraco/UmbracoDocs#2177] opened 2020-01-07 16:37 UTC
## What type of issue is it? (Choose one - delete the others)
Missing documentation

## What article/section is this about?
https://our.umbraco.com/Documentation/Umbraco-Cloud/Troubleshooting/troubleshooting-portal

## Describe the issue
Due to https://github.com/umbraco/Umbraco.Cloud.Issues/issues/66 it is possible to end up with an error with the following message: "Could not get content type with id". This error and documentation of why it happens should be added to the bulleted list of "most common errors" on the doc page along with a description of why it happens and how to fix it.

See cloud issue 66 for details, but in my notes here's one scenario: "This error happened because one document type had another document type listed as a permitted child node, and then the child document type was deleted. In this case Umbraco doesn't remove the reference from the parent node's permitted child nodes list. To solve the problem you need to find the parent node in the local env, and make a temporary change to the Permissions (see top right corner of doc type in the back office). When saving the temporary change, the reference to the old non-exististing doc type will be removed."

Also, a helpful hint to users, to find which document type an UDI/UMB represents (In Umbraco 7) look in the /data/revision folder and search for the filename containing the UDI. In VS's Solution Explorer you can filter by this UDI also.

![image](https://user-images.githubusercontent.com/15617453/71911054-4429c200-3130-11ea-9df5-5d355bd3d80c.png)

**Comment by sofietoft** [comment] 2020-01-08 09:48
Hi @tormnator !

Thanks for the report, and I can only say that I agree. We definitely should have a guide on how to troubleshoot this particular error message.
Instead of just a bullet though, I think it'd make sense to create a new article for it.
What do you think?
And would you be up for writing the article yourself? 😄 

/Sofie

**Comment by tormnator** [comment] 2020-01-08 17:17
Hi @sofietoft !

Yes, I meant for an article to be written. Unfortunately I do not (yet) have the time to write the article. I also would think someone with more insight into the Cloud data extraction process should write it. I'll be glad to provide feedback on what's written though.

-Tor

**Comment by sofietoft** [comment] 2020-02-06 10:33
Apologies for the delay here!
We're currently running tests with this scenario, in order to write an article on how to resolve it.

For some reason we're unable to reproduce this issue 🤔
Would you be able to provide us with the steps you took, when you encountered this error?
I know it's a while ago, but I hope you can help out 🤞

**Comment by jmayntzhusen** [comment] 2020-02-06 10:56
@sofietoft 
I have some notes on how / when this happens in this issue: https://github.com/umbraco/Umbraco.Cloud.Issues/issues/66#issuecomment-571951142

I think @HalldorLyngmo has been working towards a PR that will update the error message to something more useable for future Deploy versions as well 🙂

**Comment by tormnator** [comment] 2020-02-06 18:18
I'll hold off for now then. One thing, my scenario was with Umbraco 7 (latest release). Not sure if v8 changes anything.

**Comment by sofietoft** [comment] 2020-09-28 13:23
Hi all!
Apologies on the delay on this one.

The error message thrown by Deploy in cases like the one mention in this issue, has been updated.
An article about how it looks and how to resolve, has also been written. It can be found here: https://our.umbraco.com/documentation/Umbraco-Cloud/Troubleshooting/Deployments/type-not-found/

With that, I'll close this issue for now.
Should something further come up, please feel free to reopen or create a new issue.

Thanks to all who pitched in here! 💪

**Closed by sofietoft** 2020-09-28 13:23 UTC
Labels: category/missing-documentation, category/umbraco-cloud
