### ISSUE TITLE
Ability to minimise left-hand side panel?

### ISSUE THREAD

**Issue by jacksorjacksor** [umbraco/UmbracoDocs#5379] opened 2023-08-30 16:26 UTC
## What type of issue is it? (Choose one - delete the others)
Discussion / Issue

## What article/section is this about?
[All of them!](https://docs.umbraco.com/umbraco-cms)

## Describe the issue
Hi! While I may be missing one option or tick box or arrow or something, I can not find how to minimise the left-hand side panel with all of the different pages. This becomes problematic when I'm attempting to squish up one window so I can fit in everything I need to see!

![image](https://github.com/umbraco/UmbracoDocs/assets/5838388/756cb1a4-b5fb-46cd-9a6b-3bfbc5625836)

Is there any way this could be looked into - OR if it's just me missing something, please tell me where!

Using Microsoft Edge Version 116.0.1938.62

Rich

**Comment by alina-tincas** [comment] 2023-09-01 08:32
Hi @jacksorjacksor 👋 

That is a good question you have there! I have forwarded this question to our platform (Gitbook) support so let me get back to you on this. Meanwhile, I have found out that the left-hand side panel is automatically changed to a hamburger menu if the screen size is 700 or lower than 700:

![image](https://github.com/umbraco/UmbracoDocs/assets/83591955/99c2ec2f-4be3-4cbc-8f48-9eefacd0935e)

So until I get a response from Gitbook support perhaps and if possible you could try resizing the browser window to 700 or less as seen in the image above. 👍

**Comment by jacksorjacksor** [comment] 2023-09-01 08:39
Morning @alina-tincas!

Yep that's a fine (and wonderfully specific!) workaround - thank you for looking into it and forwarding over to GitBook; I appreciate what is and what is not within your control.

Cheers!
Rich

**Comment by alina-tincas** [comment] 2023-09-01 08:51
No worries @jacksorjacksor am always happy to help! Am also glad that the workaround is working for you as well 🙌 

I just got a response back from Gitbook support and they confirmed that it is not possible to set the left nav as collapsible. There is also no minimize option, and unfortunately, it is not something they are planning on adding to their product.

However what is possible is for us to remove the sidebar completely, which is not something that we would like to do. This is because we want the menu to be always available as it is easier to find the documentation articles and see as well on which one you are currently on.  

So currently as it is the workaround mentioned in my first response would be the only option. 🙏 

As there is not much we can do in this case, I am closing this issue. However, I wish to thank you again for reaching out and do not hesitate to open a new issue or [contribute ](https://docs.umbraco.com/welcome/contribute/getting-started) to our documentation. 😊

**Closed by alina-tincas** 2023-09-01 08:51 UTC
Labels: category/platform

**Comment by jacksorjacksor** [comment] 2023-09-01 09:21
@alina-tincas Ah fair! I honestly find that surprising that GitBook wouldn't offer that and hope they consider adding support in future.

I entirely agree with you - in no way should the sidebar be entirely removed, I just wish for the option to do so!

Thanks for chasing up and giving the workaround.

Rich
