### ISSUE TITLE
Document how cache refresher events work (CacheRefresherBase<PageCacheRefresher>.CacheUpdated)

### ISSUE THREAD

**Issue by Shazwazza** [umbraco/UmbracoDocs#324] opened 2016-05-02 11:34 UTC

**Comment by ZNS** [comment] 2017-01-03 10:04
Googled CacheRefresherBase and the first thing I found was this. I'd really like to see some docs on this :)

**Comment by sofietoft** [comment] 2018-01-16 11:22
See: https://github.com/umbraco/UmbracoDocs/issues/323 and https://github.com/umbraco/UmbracoDocs/issues/208

**Comment by jmayntzhusen** [comment] 2019-02-28 09:46
Hi there!

As this issue has been here for over a year without any PRs, we have decided to close it down. 
If you feel the problem is still there, then please open a new issue with as many details as you can so someone has a chance to work on it!

Thanks for reporting it in the first place! 🙂

**Closed by jmayntzhusen** 2019-02-28 09:46 UTC
Labels: category/missing-documentation
