### ISSUE TITLE
This guide is broken due to Umbraco Identity?

### ISSUE THREAD

**Issue by FransdeJong** [umbraco/UmbracoDocs#3005] opened 2021-01-30 23:00 UTC
In step 6 you should add the cloud user to the project by removing the underscore in front of the username.
In new Cloud projects the backoffice folder doesn't exist anymore. So I think this guide is now broken?

**Comment by sofietoft** [comment] 2021-02-01 08:09
Thanks for the report @FransdeJong !

Just before I start answering your question here, I want to make sure that we're on the same page.
The guide you're referring to here, is that the "[Migrate Existing site to Cloud](https://our.umbraco.com/documentation/Umbraco-Cloud/Getting-Started/Migrate-Existing-Site/)" guide?

**Comment by FransdeJong** [comment] 2021-02-01 08:35
Hi @sofietoft ,

Sorry, I clicked the button on the page so I assumed it would connect the issue with the page.
Yes it's about migrating to cloud and especially about the topic [move and merge files](https://our.umbraco.com/documentation/Umbraco-Cloud/Getting-Started/Migrate-Existing-Site/#6-move-and-merge-files).

If I start a new cloud project the backoffice folder doesn't exist anymore due to the new Umbraco Identity.
This creates a issue in the step where I need to remove the underscore.

I need to migrate another 3 sites to cloud in the upcomming 2 months but I'm afraid it is impossible to follow the guide.
The Umbraco Identity user should somehow be added to the old site.

Frans

**Comment by sofietoft** [comment] 2021-02-01 08:45
Thanks for verifying, @FransdeJong ! Usually it does actually add a link to the issue, when you clicked the button on the article 🤔  Hm! I'll look into that.

Now, for the guide here... And thanks for providing a few more details.
I've actually had it on my list to test this guide with the new Umbraco ID, as I suspected that changes might need to be made.
I believe it should still be possible, as Umbraco ID is already part of the Cloud project that you will migrate the existing site into.
So, the Umbraco ID user is not in the database (as far as I'm aware) but a set of DLL files in the project, which means you will always be able to log in to the Cloud site as long as you have an internet connection.
I do not believe that the Umbraco ID user needs to be added to the existing site before migrating, as you will be migrating **into** the Cloud site, and not the other way around 🤔 

But that's just my initial thoughts on it!
I've moved this task up on my list, and I'll run some tests a little later today, and make sure to update the guide accordingly as well - if not today, then tomorrow at the latest (unless I need some assistance from the Cloud team, then we might have to wait a few more days).

**Comment by FransdeJong** [comment] 2021-02-01 09:54
Ah, that makes sense. So the database doesn't contain the user but the project does so you can login regardless of the backoffice users in the old database. Neat!

**Comment by sofietoft** [comment] 2021-02-01 10:14
That's the theory, yes! 😄 

I'm running a test now, to verify 🤞

**Comment by sofietoft** [comment] 2021-02-01 11:00
I'm now done with my test of the migration to Cloud guide. Thanks again for making me move this up on my list, @FransdeJong 😄 

So, there are a few things I want to note here:
- The Umbraco ID user that was used to create the Cloud project, will continue to have access to the Cloud site - local and otherwise, throughout the whole process.
- Any backoffice users created on/invited to the existing site (so, before Cloud), are created in the database and will therefore also be able to login to the **local clone** of the Cloud project. However, they will **not** be able to log in on the Cloud environments, as that requires Umbraco ID.

I've already sent the information and question to our Cloud team here at Umbraco HQ, for some clarification on how to handle these existing users. Hopefully, they'll have some answers for us soon.

Other than that, when you ignore the part about the user files, the migration guide works as it should 👏 
I'll make sure to update the article and have that section about the user file removed - possibly replaced by a new section on Umbraco ID!

Let me know if you have any questions or comments!

**Comment by FransdeJong** [comment] 2021-02-01 11:28
Great news!

About the existing users. I don't mind about them not moving. There are always users that aren't active anymore and users weren't moved in the old situation either. So I wouldn't look into that if I were you.

**Comment by sofietoft** [comment] 2021-02-01 13:49
That's an interesting point of view actually 🤔 Hadn't thought about it.

But in a way it makes sense; you're moving to a new service, and your users will then need a (new) account on that service in order to continue to have access.

In any case, I've updated the migration guide now, the reflect the changes caused by Umbraco ID.
In a way - the guide is now slightly simpler than before 😄 
The biggest change is a note at the bottom of "[Step 6: Move and merge files](https://our.umbraco.com/documentation/Umbraco-Cloud/Getting-Started/Migrate-Existing-Site/#6-move-and-merge-files)".

I'll consider this issue closed for now.
As you'll be using this guide during the next couple of months - please do give me a shoutout if something doesn't work as expected!!

And thanks again for reporting this! 💪

**Closed by sofietoft** 2021-02-01 13:49 UTC
Labels: category/umbraco-cloud, state/needs-investigation
