### ISSUE TITLE
Missing - Creating Forms Based On Datasources documentation

### ISSUE THREAD

**Issue by jenistonj** [umbraco/UmbracoDocs#281] opened 2015-11-26 01:35 UTC
Broken link at
https://our.umbraco.org/documentation/Add-ons/UmbracoForms/Editor/Creating-Forms-Based-on-Datasources

**Comment by hemraker** [comment] 2015-11-30 08:18
Datasources has been added in this pull-request https://github.com/umbraco/UmbracoDocs/pull/181, needs to be updated and added to new docs structure though.

**Comment by sofietoft** [comment] 2018-01-16 10:58
@hemraker,
"Creating Forms based on Datasources", was that a guide that existed at some point?
Also, the PR you linked to, has been closed due to inactivity 🙈 

-Sofie

**Comment by marcemarc** [comment] 2018-04-10 16:04
This is a duplicate of: https://github.com/umbraco/UmbracoDocs/issues/254

**Closed by marcemarc** 2018-04-10 16:04 UTC
Labels: Umbraco Forms, broken link, duplicate
