### ISSUE TITLE
Building a form with a GET action

### ISSUE THREAD

**Issue by Shazwazza** [umbraco/UmbracoDocs#336] opened 2016-05-12 08:38 UTC
Need to document there various ways this can be achieved

**Comment by jmayntzhusen** [comment] 2019-02-28 09:46
Hi there!

As this issue has been here for over a year without any PRs, we have decided to close it down. 
If you feel the problem is still there, then please open a new issue with as many details as you can so someone has a chance to work on it!

Thanks for reporting it in the first place! 🙂

**Closed by jmayntzhusen** 2019-02-28 09:46 UTC
Labels: category/missing-documentation
