### ISSUE TITLE
Migrated Angular tutorials to these docs

### ISSUE THREAD

**Issue by Shazwazza** [umbraco/UmbracoDocs#204] opened 2015-08-21 13:48 UTC
The tutorials here: http://umbraco.github.io/Belle/#/api

need to be migrated/updated/etc... to these docs.

**Comment by sofietoft** [comment] 2018-01-15 14:44
Hi @Shazwazza 

Is this simply a copy/paste thing?
Or perhaps I should ask, whether it's still relevant? 🤔 

- Sofie

**Comment by hemraker** [comment] 2018-01-15 17:58
@sofietoft it's done == https://our.umbraco.org/documentation/Reference/#backoffice-ui-api-documentation

Can be closed down 🙂

**Comment by Shazwazza** [comment] 2018-01-16 03:45
These are the 'tutorials' i'm talking about here: http://umbraco.github.io/Belle/#/tutorials

Not the API docs part. I'm unsure if all of these have been migrated or not, would need to check in the current docs to confirm. (then we should close down that Belle site!)

**Comment by marcemarc** [comment] 2018-01-19 11:02
@sofietoft @Shazwazza @hemraker what I think is we need a new section in the main documentation for 'Running Umbraco from Source' or possibly as part of a 'How to contribute to Umbraco section' - see related: https://github.com/umbraco/UmbracoDocs/issues/222 and we should sanity check The 'running a nightly build' and 'Building from source' tutorials to move here.  Also the 'How the code is structured' details could be added here. 

The property editor tutorials though cover pretty much the same as those in the documentation here: https://our.umbraco.org/documentation/Extending/Property-Editors/ but we have another issue reported on the tutorial (https://github.com/umbraco/UmbracoDocs/issues/274) so maybe the task is to cross reference the two, run through the tutorial in latest Umbraco version leaving one great Property Editor creation tutorial in the docs.

There is also the infamous AngularWorkshop: https://github.com/umbraco/AngularWorkbook/ which crosses over into a bit of an introduction to how Angular works generally, as well as extending the backoffice - worth seeing if some of this material is useful for a 'How to contribute to Umbraco' section -  there is overlap with the existing documentation tutorial for creating a property editor and of course the content of the 'extending the backoffice' training course, but I suspect there are 'some bits' only found here.

**Comment by jmayntzhusen** [comment] 2019-02-28 09:43
Hi there!

As this issue has been here for over a year without any PRs, we have decided to close it down. 
If you feel the problem is still there, then please open a new issue with as many details as you can so someone has a chance to work on it!

Thanks for reporting it in the first place! 🙂

**Closed by jmayntzhusen** 2019-02-28 09:43 UTC
Labels: category/missing-documentation
