### ISSUE TITLE
Example of generating blocklist values during an event

### ISSUE THREAD

**Issue by jemayn** [umbraco/UmbracoDocs#3645] opened 2021-11-17 20:04 UTC
## What type of issue is it? (Choose one - delete the others)
Missing documentation

## Describe the issue

Would love some documentation on how to generate blocklist values in an EditorModel event. 

I found that the value a blocklist will have during content load is the `Umbraco.Core.Models.Blocks.BlockValue` model, however creating that seems very complex, and I haven't been able to get it to work.

**Comment by eshanrnh** [comment] 2022-07-01 08:11
Hey @jemayn 👋,

It's been quite some time since the issue was raised. Can you please confirm if the issue is still relevant and you need some more information on generating blocklist values in an EditorModel event?

**Comment by sofietoft** [comment] 2022-07-07 08:06
Hi @jemayn !

It's been a while since we've heard back from you here, so we'll be closing this issue for now.
Please do not hesitate to get back in touch, should you have further comments or questions.

Thanks again for helping us keep the docs up to date 😄 💪

**Closed by sofietoft** 2022-07-07 08:06 UTC
Labels: category/code-example, community/up-for-grabs
