### ISSUE TITLE
No documentation for ignoring Angular HTTP errors

### ISSUE THREAD

**Issue by abjerner** [umbraco/UmbracoDocs#501] opened 2017-07-11 15:13 UTC
UmbracoCms has an interceptor hooked into the `$http` Angular service, and will trigger an error message if a request responds with a 404 error code.

It _is_ possible to tell Umbraco to ignore these errors - either by specifying the `x-umb-ignore-error` request header or the `umbIgnoreErrors` config option. But as far as I can tell, neither of these are mentioned anywhere in the documentation.

I'd be happy to write a few lines on how to use this in code, but I'm not sure where in the documentation something like this belongs, so I have created this issue instead. Anyone from the HQ that can point me in the right direction?

A little extra info here: http://issues.umbraco.org/issue/U4-5588

**Comment by sofietoft** [comment] 2018-01-16 14:37
@Shazwazza,
Do you have an idea of a good place to put documentation about this?

**Comment by Shazwazza** [comment] 2018-02-05 05:07
Would probably create another category in `Reference` since this is a pretty technical concept. A new category could be called UI Development or Angular Development or similar

**Comment by jmayntzhusen** [comment] 2019-02-28 09:47
Hi there!

As this issue has been here for over a year without any PRs, we have decided to close it down. 
If you feel the problem is still there, then please open a new issue with as many details as you can so someone has a chance to work on it!

Thanks for reporting it in the first place! 🙂

**Closed by jmayntzhusen** 2019-02-28 09:47 UTC
Labels: category/missing-documentation
