### ISSUE TITLE
Create packaging docs for the 'Extending' section

### ISSUE THREAD

**Issue by Shazwazza** [umbraco/UmbracoDocs#209] opened 2015-08-21 14:50 UTC

**Comment by jmayntzhusen** [comment] 2019-02-28 09:44
Hi there!

As this issue has been here for over a year without any PRs, we have decided to close it down. 
If you feel the problem is still there, then please open a new issue with as many details as you can so someone has a chance to work on it!

Thanks for reporting it in the first place! 🙂

**Closed by jmayntzhusen** 2019-02-28 09:44 UTC
Labels: category/missing-documentation
