### ISSUE TITLE
Surface Controller page routes are wrong

### ISSUE THREAD

**Issue by skartknet** [umbraco/UmbracoDocs#734] opened 2018-04-05 23:43 UTC
The routes displayed here: https://our.umbraco.org/documentation/reference/routing/surface-controllers
are incorrect. It looks like some details have disappeared:

![image](https://user-images.githubusercontent.com/1685262/38397054-da8900a4-397e-11e8-872e-bac9b7b1fe48.png)

**Comment by skartknet** [comment] 2018-04-05 23:49
The MD file looks correct. There must be an issue with the rendering of it into the site:

![image](https://user-images.githubusercontent.com/1685262/38397210-ca779508-397f-11e8-85f8-e6f1182a122f.png)

**Comment by dampee** [comment] 2018-04-06 19:12
Thanks a lot for bringing this to our attention.  We will look at this asap.

**Comment by marcemarc** [comment] 2018-04-06 22:44
@Jeavon wondered if this was related to the change from MarkdownDeep to Markdig for the converter?

**Comment by Jeavon** [comment] 2018-04-09 14:57
hmm, something is parsing out the braces, I think it's probably the link parser, but I'll check

**Comment by Jeavon** [comment] 2018-04-10 09:04
This is indeed a issue with Markdig, I have created a workaround. Closing this issue as the issue is with Our not the Docs themselves. https://github.com/umbraco/OurUmbraco/pull/226/files

**Closed by Jeavon** 2018-04-10 09:04 UTC

**Comment by nul800sebastiaan** [comment] 2018-04-10 12:51
Thanks! Fix has been deployed and the page looks good again.
