### ISSUE TITLE
Missing ressource for the Tutorial : Creating a property editor

### ISSUE THREAD

**Issue by AnassL** [umbraco/UmbracoDocs#274] opened 2015-11-13 12:04 UTC
I am following the tutorial [here!](https://our.umbraco.org/documentation/Tutorials/Creating-a-Property-Editor/) but found no markdown.css file sample in the tutorial. Is there any code source for this tutorial to compare with the found results ?

**Comment by hemraker** [comment] 2015-11-30 08:13
Right we need to update the tutorial with some up to date assets.

Thanks for raising the issue!!

**Comment by sofietoft** [comment] 2018-01-16 10:08
A task for you, @hemraker? 
Or perhaps the entire tutorial needs an overhaul?

**Comment by hemraker** [comment] 2018-01-16 10:27
A bit of both ;)

**Comment by jmayntzhusen** [comment] 2019-02-28 09:45
Hi there!

As this issue has been here for over a year without any PRs, we have decided to close it down. 
If you feel the problem is still there, then please open a new issue with as many details as you can so someone has a chance to work on it!

Thanks for reporting it in the first place! 🙂

**Closed by jmayntzhusen** 2019-02-28 09:45 UTC
Labels: category/missing-documentation
