### ISSUE TITLE
Minor typo: "Rollback to a Previous Versions"

### ISSUE THREAD

**Issue by tormnator** [umbraco/UmbracoDocs#3975] opened 2022-05-19 20:19 UTC
Should say: "Rollback to a Previous Version".

***This is the page with issues: https://github.com/umbraco/UmbracoDocs/edit/main/Tutorials/Editors-Manual/Version-Management/index.md***

**Comment by eshanrnh** [comment] 2022-05-20 07:27
Thanks for reporting the typo, @tormnator 💪

The issue is now fixed. 🙂

**Closed by eshanrnh** 2022-05-20 07:27 UTC
Labels: category/umbraco-cms
