### ISSUE TITLE
Media Picker allows svg

### ISSUE THREAD

**Issue by JonathonCove** [umbraco/UmbracoDocs#2408] opened 2020-03-30 14:31 UTC
Apologies, I can't find a better place to log this.

***This is the page with issues: https://github.com/umbraco/UmbracoDocs/edit/master/Getting-Started/Backoffice/Property-Editors/Built-in-Property-Editors/Media-Picker/index.md***

When ticking 'pick only images' this allows the upload of SVG files. However, SVG files can't be parsed as PublishedModels.Image , so creating a picker for images and parsing the picked file as an image in code will cause an error.

**Comment by nul800sebastiaan** [comment] 2020-03-31 06:30
Hi @JonathonCove, what does that mean "SVG files can't be parsed as PublishedModels.Image"?

**Comment by sofietoft** [comment] 2020-04-16 06:30
Hi @JonathonCove !

It's been a while since we've heard from you here.
Did you see Sebastiaans question? 😊

**Comment by JonathonCove** [comment] 2020-04-16 08:05
Hi Both

Yes sorry, this required a lot of explanation.

So I've created a Data Type called 'Image uploader single' which is a media picker that allows only images:
![image](https://user-images.githubusercontent.com/12764069/79429573-9431e380-7fbf-11ea-9b61-f61c7d5328df.png)

When using this picker, it allows me to select images, including SVGs.

I can then access this image in my razor view, like so: `Image theImage = (Image)Model.Image;` 

However, an SVG image cannot be converted to an `Image`, and an error is thrown. 

This could be a misunderstanding on my part, and I apologise for taking up your time if that's the case, but I assumed ticking 'Pick only images' would mean everything picked could be of type `Image` 

I hope that makes more sense!

**Comment by sofietoft** [comment] 2020-04-17 08:14
Thanks for explaining!

So, when you have a MediaPicker with the "Pick only images" option checked, it still lets you select SVG images, which aren't rendered on the frontend.
Am I understanding that correctly?

I'll have a shot at reproducing. Might be something that needs to be reporting on the CMS Issue tracker.

**Comment by sofietoft** [comment] 2020-04-17 09:52
I've now spent some time, trying to reproduce this issue - and so far, I've been unable to.

When you render the image on the frontend, are you using the snippets from this article: https://our.umbraco.com/documentation/getting-started/backoffice/property-editors/built-in-property-editors/media-picker/ ?
There are some samples in the bottom of the page, and when I use those, I can render out the SVG files just fine on the frontend 🤔

**Comment by sofietoft** [comment] 2020-04-30 08:18
Hi @JonathonCove - I haven't heard back from you a while did.

Did you manage to show your SVG files on your frontend? :)

**Comment by sofietoft** [comment] 2020-05-26 09:57
Hi @JonathonCove 

It's been a while since I've seen any activity on this one - hope that means you managed to render out the SVG file on the frontend 💪 

I'll be closing this issue for now.
Please feel free to re-open it, should you continue to struggle with the SVGs!
And thanks again for the report!

**Closed by sofietoft** 2020-05-26 09:57 UTC
Labels: state/needs-more-info
