### ISSUE TITLE
Docs suggest one can override ValidateSettings for a FieldType but this is not possible

### ISSUE THREAD

**Issue by rustybox** [umbraco/UmbracoDocs#1739] opened 2019-06-18 10:58 UTC
> The ValidateSettings() method which can be found on all types supporting dynamic settings, is used for making sure the data entered by the user is valid and works with the type.

FieldType supports dynamic settings, but does not have a method ValidateSettings to override.

***This is the page with issues: https://github.com/umbraco/UmbracoDocs/edit/master/Add-ons/UmbracoForms/Developer/Extending/Adding-a-Type.md***

**Comment by sofietoft** [comment] 2020-03-05 09:41
Hi @rustybox !

Apologies for taking so long to get back to you.
I can tell you now, that this issue is being investigated!

Just out of curiosity: Did you manage to find a solution to this yourself? 😄

**Comment by rustybox** [comment] 2020-03-05 09:53
I believe the workaround was just creating a new field type that didn't inherit.

**Comment by sofietoft** [comment] 2020-10-23 07:16
Hi @rustybox 
I have an update for you, on this one.
Turns out that what you have found here is a bug in Umbraco Forms.
One of our Forms experts have been able to reproduce - it's like the code snippet from the Docs doesn't get triggered 🤔

An issue has been created on the Forms Issue tracker: https://github.com/umbraco/Umbraco.Forms.Issues/issues/433 

How about we add a warning in the docs about this bug, until it's resolved? What do you think?

**Comment by rustybox** [comment] 2020-10-23 07:46
Seems reasonable

**Comment by sofietoft** [comment] 2020-10-23 07:51
Super. I'll make sure that's done.
I've subscribed to the Forms issue, so I'll know when the bug is resolved and when to remove the warning from the docs again.

I'll close this issue for now.
Thanks again for making us aware of this 💪 Much appreciated.

**Closed by sofietoft** 2020-10-23 07:51 UTC
Labels: category/umbraco-forms, state/needs-investigation

**Comment by sofietoft** [comment] 2020-10-23 08:17
The warning has now been added to the article: https://our.umbraco.com/documentation/Add-ons/UmbracoForms/Developer/Extending/Adding-a-Type#validate-type-settings-with-validatesettings
