### ISSUE TITLE
Add documentation for tag support (creating property editors)

### ISSUE THREAD

**Issue by hemraker** [umbraco/UmbracoDocs#230] opened 2015-09-01 07:03 UTC
The example for c# is very limited IMO and none exists for manifest (if this is possible)

https://our.umbraco.org/documentation/Extending/Property-Editors/tag-support
http://umbraco.github.io/Belle/#/tutorials/Tag-Enabled-Property-Editors

**Comment by sofietoft** [comment] 2018-01-16 09:48
Yo!

Is this by any chance related to this one: https://github.com/umbraco/UmbracoDocs/issues/170 ?

-Sofie

**Comment by Shazwazza** [comment] 2018-02-05 05:08
Yes they are related

**Comment by jmayntzhusen** [comment] 2019-02-28 09:45
Hi there!

As this issue has been here for over a year without any PRs, we have decided to close it down. 
If you feel the problem is still there, then please open a new issue with as many details as you can so someone has a chance to work on it!

Thanks for reporting it in the first place! 🙂

**Closed by jmayntzhusen** 2019-02-28 09:45 UTC
Labels: category/missing-documentation, community/up-for-grabs, help wanted
